name: tools
description: Usefull Tools For Flutter Developers
version: 0.0.1
homepage: ''

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_adaptive_ui: 0.8.0+1
  url_launcher: 6.1.14
  shared_preferences: 2.1.1
  cached_network_image: 3.3.1
  toast: 0.3.0

  # share_plus: 6.3.1
  clipboard: 0.1.3 #0.1.3
  url_strategy: 0.2.0
  auto_size_text: 3.0.0
  # connectivity_plus: any #2.3.6
  # device_info_plus: 4.1.2 #9.0.2
  infinite_scroll_pagination: 3.2.0 #3.2.0
  # flutter_slidable: any #2.0.0
  image_picker: 0.8.7+5
  photo_view: 0.14.0
  shamsi_date: 1.0.1
  http: 1.1.2
  dio: 5.1.2


  # dartz: any


  # test
  flutter_inset_box_shadow: 1.0.8
  flutter_rating_bar: 4.0.1
  logging: 1.1.1
  universal_platform: 1.0.0+1
  # motion_toast: 2.6.7

  # get_it: 7.6.0
  # provider: 6.0.5
  # file_picker: 5.3.0



  # jiffy: 5.0.0
  jiffy: 6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
  # dart_code_metrics: ^5.6.0

  # flutter packages pub run build_runner build

flutter:
