name: tools
description: Usefull Tools For Flutter Developers
version: 0.0.1
homepage: ''

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_adaptive_ui: 0.8.0+1
  url_launcher: 6.3.0
  # url_launcher_ios: 6.3.1
  # url_launcher_android: 6.3.10
  shared_preferences: 2.3.2
  cached_network_image: 3.4.1
  toast: 0.3.0
  flutter_secure_storage: 9.2.2
  share_plus: 10.0.2
  clipboard: 0.1.3
  url_strategy: 0.3.0
  auto_size_text: 3.0.0
  # connectivity_plus: any #2.3.6
  # device_info_plus: 4.1.2 #9.0.2
  infinite_scroll_pagination: 4.0.0
  # flutter_slidable: any #2.0.0
  image_picker: 1.1.2
  photo_view: 0.15.0
  shamsi_date: 1.0.4
  http: 1.2.2
  dio: 5.7.0
  pretty_dio_logger: 1.4.0


  # dartz: any


  # test
  flutter_inset_box_shadow: 1.0.8
  flutter_rating_bar: 4.0.1
  logging: 1.2.0
  universal_platform: 1.1.0
  # motion_toast: 2.6.7

  # get_it: 7.6.0
  # provider: 6.0.5
  # file_picker: 5.3.0



  # jiffy: 5.0.0
  jiffy: 6.3.1
  web: 1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  # dart_code_metrics: ^5.6.0

  # flutter packages pub run build_runner build

flutter:
